fullnameOverride: backend-service

backend:
  name: backend 
  replicaCount: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  image:
    repository: ghcr.io/nguyentukien/pharmagent-backend:latest
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8080
  environment:
    COR_ALLOWED_ORIGINS: "*"

database:
  service:
    host: "database-pharmagent-nodeport"
    port: 27017
  environment:
    MONGO_DATABASE: PharmAgentDB
    MONGO_USER: "<set-via-secret>"
    MONGO_PASSWORD: "<set-via-secret>"

redis:
  service:
    host: "redis-12088.c325.us-east-1-4.ec2.cloud.redislabs.com"
    port: 12088
  environment:
    REDIS_USER: "<set-via-secret>"
    REDIS_PASSWORD: "<set-via-secret>"

rabbitmq:
  service:
    host: "gerbil.rmq.cloudamqp.com"
    port: 5671
  environment:
    RABBITMQ_USER: "<set-via-secret>"
    RABBITMQ_PASSWORD: "<set-via-secret>"
    RABBITMQ_VHOST: "<set-via-secret>"

mail:
  environment:
    SPRING_MAIL_USERNAME: "<set-via-secret>"
    SPRING_MAIL_PASSWORD: "<set-via-secret>"
    SPRING_MAIL_HOST: "smtp.gmail.com"
    SPRING_MAIL_PORT: "587"

security:
  environment:
    JWT_SECRET: "<set-via-secret>"
