backend:
  name: backend 
  replicaCount: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  image:
    repository: ghcr.io/nguyentukien/pharmagent-backend:latest
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8080
  environment:
    COR_ALLOWED_ORIGINS: "*"

database:
  service:
    host: "database-pharmagent-nodeport"
    port: 27017
  environment:
    MONGO_DATABASE: PharmAgentDB
    MONGO_USER: appUser
    MONGO_PASSWORD: appPassword123

redis:
  service:
    host: "redis-12088.c325.us-east-1-4.ec2.cloud.redislabs.com"
    port: 12088
  environment:
    REDIS_USER: "default"
    REDIS_PASSWORD: "hM3tdC4ETyAOXeoAtHjwKbHyTYJd6Wfq"

rabbitmq:
  service:
    host: "gerbil.rmq.cloudamqp.com"
    port: 5671
  environment:
    RABBITMQ_USER: "guest"
    RABBITMQ_PASSWORD: "M9Em_GaseLCVB2pfFGVhoUD"
    RABBITMQ_VHOST: "/"

mail:
  environment:
    SPRING_MAIL_USERNAME: "thechalksquad.work@gmail.com"
    SPRING_MAIL_PASSWORD: "vxagswcsettletgb"
    SPRING_MAIL_HOST: "smtp.gmail.com"
    SPRING_MAIL_PORT: "587"

security:
  environment:
    JWT_SECRET: "VGhpc0lzQURldlNlY3JldEtleUZvckpXVFNpZ25pbmdPbmx5ISE="