spring:
  main:
    banner-mode: "off"
  application:
    name: backend
  mongodb:
    uri: mongodb+srv://admin:Nhom06_LTW@clustertest.xg7jkii.mongodb.net/PharmAgentDB?retryWrites=true&w=majority&authSource=admin

logging:
  level:
    root: info