spring:
  main:
    banner-mode: "off"
  application:
    name: backend
  data:
    mongodb:
      uri: mongodb://${MONGO_INITDB_USERNAME}:${MONGO_INITDB_PASSWORD}@${DB_HOST}:${DB_PORT}/${MONGO_INITDB_DATABASE}?authSource=${MONGO_INITDB_DATABASE}

logging:
  level:
    root: warn