apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ include "helm.fullname" . }}-configmap'
  labels:
    {{- include "helm.labels" . | nindent 4 }}
data:
  # Database configuration
  SPRING_MONGODB_HOST: "{{ .Values.database.service.host }}"
  SPRING_MONGODB_PORT: "{{ .Values.database.service.port }}"
  SPRING_MONGODB_DATABASE: "{{ .Values.database.environment.MONGO_DATABASE }}"
  SPRING_MONGODB_USERNAME: "{{ .Values.database.environment.MONGO_USER }}"
  {{- if eq .Values.database.service.protocol "mongodb+srv" }}
  SPRING_MONGODB_URI: "mongodb+srv://{{ .Values.database.service.host }}/{{ .Values.database.environment.MONGO_DATABASE }}"
  {{- else }}
  SPRING_MONGODB_URI: "mongodb://{{ .Values.database.service.host }}:{{ .Values.database.service.port }}/{{ .Values.database.environment.MONGO_DATABASE }}"
  {{- end }}

  # Redis configuration
  SPRING_DATA_REDIS_HOST: "{{ .Values.redis.service.host }}"
  SPRING_DATA_REDIS_PORT: "{{ .Values.redis.service.port }}"
  SPRING_DATA_REDIS_USERNAME: "{{ .Values.redis.environment.REDIS_USER }}"
  SPRING_DATA_REDIS_URL: "redis://{{ .Values.redis.service.host }}:{{ .Values.redis.service.port }}"

  # RabbitMQ configuration
  SPRING_RABBITMQ_HOST: "{{ .Values.rabbitmq.service.host }}"
  SPRING_RABBITMQ_PORT: "{{ .Values.rabbitmq.service.port }}"
  SPRING_RABBITMQ_USERNAME: "{{ .Values.rabbitmq.environment.RABBITMQ_USER }}"
  SPRING_RABBITMQ_VIRTUAL_HOST: "{{ .Values.rabbitmq.environment.RABBITMQ_VHOST }}"
  SPRING_RABBITMQ_ADDRESSES: "{{ .Values.rabbitmq.service.host }}:{{ .Values.rabbitmq.service.port }}"

  # Mail configuration
  SPRING_MAIL_USERNAME: "{{ .Values.mail.environment.SPRING_MAIL_USERNAME }}"

  # Other configuration
  CORS_ALLOWED_ORIGINS: "{{ .Values.backend.environment.COR_ALLOWED_ORIGINS }}"