apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ include "helm.fullname" . }}-configmap'
  labels:
    {{- include "helm.labels" . | nindent 4 }}
data:
  # MongoDB configuration
  {{- if eq .Values.database.service.protocol "mongodb+srv" }}
  SPRING_MONGODB_URI: "mongodb+srv://{{ .Values.database.service.host }}/{{ .Values.database.environment.MONGO_DATABASE }}?retryWrites=true&w=majority"
  {{- else }}
  SPRING_MONGODB_URI: "mongodb://{{ .Values.database.service.host }}:{{ .Values.database.service.port }}/{{ .Values.database.environment.MONGO_DATABASE }}"
  {{- end }}

  # Redis configuration
  SPRING_DATA_REDIS_URL: "redis://{{ .Values.redis.service.host }}:{{ .Values.redis.service.port }}"

  # RabbitMQ configuration
  SPRING_RABBITMQ_ADDRESSES: "{{ .Values.rabbitmq.service.host }}:{{ .Values.rabbitmq.service.port }}"

  # Mail configuration
  SPRING_MAIL_USERNAME: "{{ .Values.mail.environment.SPRING_MAIL_USERNAME }}"

  # Other configuration
  CORS_ALLOWED_ORIGINS: "{{ .Values.backend.environment.COR_ALLOWED_ORIGINS }}"