apiVersion: v1
kind: Secret
metadata:
  name: '{{ include "helm.fullname" . }}-secret'
  labels:
    {{- include "helm.labels" . | nindent 4 }}
type: Opaque
stringData:
  # MongoDB configuration
  SPRING_MONGODB_USERNAME: "{{ .Values.database.environment.MONGO_USER }}"
  SPRING_MONGODB_PASSWORD: "{{ .Values.database.environment.MONGO_PASSWORD }}"
  {{- if eq .Values.database.service.protocol "mongodb+srv" }}
  SPRING_MONGODB_URI: "mongodb+srv://{{ .Values.database.environment.MONGO_USER }}:{{ .Values.database.environment.MONGO_PASSWORD }}@{{ .Values.database.service.host }}/{{ .Values.database.environment.MONGO_DATABASE }}?retryWrites=true&w=majority&tls=true"
  {{- else }}
  SPRING_MONGODB_URI: "mongodb://{{ .Values.database.environment.MONGO_USER }}:{{ .Values.database.environment.MONGO_PASSWORD }}@{{ .Values.database.service.host }}:{{ .Values.database.service.port }}/{{ .Values.database.environment.MONGO_DATABASE }}"
  {{- end }}  
  
  # Redis configuration
  SPRING_DATA_REDIS_PASSWORD: "{{ .Values.redis.environment.REDIS_PASSWORD }}"
  SPRING_DATA_REDIS_URL: "redis://{{ .Values.redis.environment.REDIS_USER }}:{{ .Values.redis.environment.REDIS_PASSWORD }}@{{ .Values.redis.service.host }}:{{ .Values.redis.service.port }}"
  
  # RabbitMQ configuration
  SPRING_RABBITMQ_USERNAME: "{{ .Values.rabbitmq.environment.RABBITMQ_USER }}"
  SPRING_RABBITMQ_PASSWORD: "{{ .Values.rabbitmq.environment.RABBITMQ_PASSWORD }}"
  
  # Mail & Security
  SPRING_MAIL_PASSWORD: "{{ .Values.mail.environment.SPRING_MAIL_PASSWORD }}"
  JWT_SECRET: "{{ .Values.security.environment.JWT_SECRET }}"